name: CD - Deploy FastAPI App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv env
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy Application
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.SSH_HOST }}
            USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 400 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} << 'EOF'
          cd ~/hng12-stage2-fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip3 install -r requirements.txt
            sudo systemctl restart fastapi-app
          EOF
